["./wezterm"]
type = "git-repo"
url = "https://github.com/nnmchang/wezterm-config.git"
refreshPeriod = "168h"

["./nvim"]
type = "git-repo"
url = "https://github.com/nnmchang/nvim.git"
refreshPeriod = "168h"

["./delta"]
type = "git-repo"
url = "https://github.com/catppuccin/delta.git"
refreshPeriod = "168h"
