["./wezterm"]
type = "git-repo"
url = "https://github.com/nnmchang/wezterm-config.git"
refreshPeriod = "168h"

["./nvim"]
type = "git-repo"
url = "https://github.com/nnmchang/nvim.git"
refreshPeriod = "168h"

["./delta/catppuccin.gitconfig"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/delta/main/catppuccin.gitconfig"
refreshPeriod = "168h"
