packages:
  brew:
    - ripgrep
    - fd
    - fzf
    - git
    - pkg-config
    - lazygit
    - neovim
    - mise
    - starship
    - sheldon
    - vivid
    - lsd
    - yazi
    - zoxide
    - git-delta
    - gh
    - bat
    - bottom
    - sd
    - dust
    - duf
    - procs
    - jq
    - yq
  scoop:
    - git
    - 7zip
    - fd
    - fzf
    - ripgrep
    - zig
    - make
    - yazi
    - zoxide
    - gh
    - neovim
    - extras/lazygit
    - starship
    - lsd
    - delta
    - bat
    - bottom
    - gsudo
    - sd
    - dust
    - duf
    - procs
    - less
    - grep
    - sed
    - gawk
    - uutils-coreutils
    - uutils-findutils
    - jq
    - yq
