packages:
  brew:
    - ripgrep
    - fd
    - fzf
    - git
    - pkg-config
    - lazygit
    - neovim
    - mise
    - starship
    - sheldon
    - vivid
    - lsd
    - rust-analyzer
    - yazi
    - zoxide
    - git-delta
    - gh
    - bat
    - bottom
  scoop:
    - 7zip
    - fd
    - fzf
    - ripgrep
    - zig
    - make
    - yazi
    - zoxide
    - gh
    - neovim
    - extras/lazygit
    - starship
    - lsd
    - delta
    - bat
    - bottom
    - gsudo
mise:
  - tool: python
    version: "3.12.3"
    use: "global"
  - tool: python
    version: "3.13-dev"
