name: GitHub Actions CI
on:
  push:
    branches: main
  pull_request:
jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: Install Homebrew
      run: |
        '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
        'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    - name: Insta;; Chezmoi
      run: 'brew install chezmoi'
    - name: Test Chezmoi
      run: 'chezmoi init --apply -S .'
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: PowerShell Policy
      run: 'Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force'
    - name: Install Scoop
      uses: MinoruSekine/setup-scoop@v4
    - name: Install Chezmoi
      run: 'scoop install chezmoi'
    - name: Test Chezmoi Windows
      run: 'chezmoi init --apply -S .'
