name: GitHub Actions CI
on:
  push:
    branches: main
  pull_request:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        
    steps:
      
    - name: Set up Git repository
      uses: actions/checkout@v4
      with:
        path: ../.local/share/chezmoi

    - name: Test Chezmoi
      run: 'sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply'
