name: GitHub Actions CI
on:
  push:
    branches: main
  pull_request:
jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: Set up homebrew
      uses: 'Homebrew/actions/setup-homebrew@master'
    - name: Install Chezmoi
      run: 'brew install chezmoi'
    - name: Test Chezmoi
      run: 'chezmoi init --apply --source $GITHUB_WORKSPACE'
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: PowerShell Policy
      run: 'Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force'
    - name: Install Scoop
      uses: MinoruSekine/setup-scoop@v4
    - name: Install Chezmoi
      run: 'scoop install chezmoi'
      shell: powershell
    - name: Test Chezmoi Windows
      run: 'chezmoi init --apply --source $Env:GITHUB_WORKSPACE'
